[workspace]
members = ["programs/fantasy_sports"]

[toolchain]
anchor_version = "0.31.1"

[programs.devnet]
fantasy_sports = "3x7u6RMoygDW5nHB8cFk3cdrm3qMsPLgjDPPmchRTEqX"

[programs.localnet]
fantasy_sports = "3x7u6RMoygDW5nHB8cFk3cdrm3qMsPLgjDPPmchRTEqX"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -r ts-node/register tests/**/*.ts"

