[workspace]
members = ["programs/fantasy_sports"]

[toolchain]
anchor_version = "0.31.1"

[programs.devnet]
fantasy_sports = "4gUqFwJxDDQsgd3qhoGhx42nJo9QHszXy6RdN53AVzjp"

[programs.localnet]
fantasy_sports = "4gUqFwJxDDQsgd3qhoGhx42nJo9QHszXy6RdN53AVzjp"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -r ts-node/register tests/**/*.ts"

