[workspace]
members = ["programs/fantasy_sports"]

[toolchain]
anchor_version = "0.31.1"

[programs.devnet]
fantasy_sports = "2yj1FY4Q7TPL3x5Zyuu8PhKv89A9QTGm5pJdDrbNs9My"

[programs.localnet]
fantasy_sports = "2yj1FY4Q7TPL3x5Zyuu8PhKv89A9QTGm5pJdDrbNs9My"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
