[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fantasy_sports = "8WbSTYKCQa2cuL3tZeMbfwwBaAaVvxCQbwnpHGM2HGwV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
