[workspace]
members = ["programs/fantasy_sports"]

[toolchain]
anchor_version = "0.31.1"

[programs.devnet]
fantasy_sports = "4ATf8K3EfcdT1RVKUybE95DSF9nZ3rhD9s9mathPPrDy"

[programs.localnet]
fantasy_sports = "4ATf8K3EfcdT1RVKUybE95DSF9nZ3rhD9s9mathPPrDy"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -r ts-node/register tests/**/*.ts"

[features]
skip-lint = true
