[workspace]
members = ["programs/fantasy_sports"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "1.18.15"

[profile.release]
overflow-checks = true
